---
title: Klassendiagramm
---
classDiagram
    class SnackMachine{
        - List~Snack~ snacks
        - CoinStack coinStorage
    }
    class Snack{
        + String name
        + int price
        + int amount
        + reduce()
    }
    
    class CoinStack{
        -Map<Coin, int> _coins
        +int get sum
        +void addCoin(Coin)
        +void removeCoin(Coin)
        +int getCoinAmount(Coin type)
        +bool hasCoinOfType(Coin coinType)
        +Coin? tryGetHighestCoinBelowAmount(int amount)
        +void clear()
        +void setRandom()
        +void setStack(Map<Coin, int> newStack)
    }
    class Coin{
        <<enumeration>>
        euro2
        euro1
        cent50
        cent20
        cent10
        cent5
        cent2
        cent1
        
        +int worth
    }
    class VendingState{
        <<abstract>>
            +VendingState onSnackSelected()
            +VendingState onCoinInserted()
            +VendingState onReturnPressed()
        }
        
    class IdleState{
    }
    class NoSelectionState{}

SnackMachine "1" o-- "0..*" Snack: contains
SnackMachine "1" o-- "1" CoinStack: contains
SnackMachine "1" o-- "1" VendingState: has
CoinStack "1" *-- "0..n" Coin: consits of
VendingState <|-- IdleState
VendingState <|-- NoSelectionState