erDiagram
    VENDING_MACHINE ||--o{ COIN_STACK : "1:2"
    VENDING_MACHINE ||--o{ SNACK_SLOT : "1:n"
    VENDING_MACHINE ||--|| VENDING_STATE : "1:1"
    SNACK_SLOT }|--|| SNACK : "n:1"

    VENDING_MACHINE {
        int id PK "CHECK (id = 1) (Singleton)"
        int coinStorageID FK "0"
        int changeID FK "1"
    }

    COIN_STACK {
        int id PK
        json tresorCoins "Map<Coin, int>" 
        json returnCoins "Map<Coin, int>"
    }

    SNACK_SLOT {
        int id PK
        int vendingMachineId FK
        int snackId FK
        int count
    }

    SNACK {
        int id PK
        string name
        int priceInCents "In Cent!"
    }

    VENDING_STATE {
        int id PK "CHECK (id = 1) (Singleton)"
        int vendingMachineId FK
        string type 
        int selectedSnackId FK
        int insertedCoinsInCents "In Cent!"
    }