stateDiagram-v2
    idle
    waitCoins: Wait for Coins
    noSnack: No Snack Selected

    dispCoins: Dispense Coins
    dispSnack: Dispense Snack

    dPrice: Price Paid?
    dSnack: Snack in stock?
    dReturn: Return Possible?
    state snack_av <<choice>>
    dSnack --> snack_av
    state price_paid <<choice>>
    dPrice --> price_paid
    state return_possible <<choice>> 
    dReturn --> return_possible

    [*]-->idle
    AnyManualState --> dispCoins : return pressed
    dispCoins --> idle : onFinished 
    idle --> dSnack : select snack
    idle --> noSnack: insert coin


    noSnack --> noSnack: insertCoin
    noSnack --> dSnack: select snack

    snack_av --> dPrice : YES
    snack_av --> noSnack : NO


    price_paid --> dReturn: YES
    price_paid --> waitCoins: NO


    waitCoins --> dPrice: insert coin
    waitCoins --> dSnack: snack selected

    return_possible --> dispSnack: YES
    return_possible --> noSnack: NO

    dispSnack --> noSnack: on finished

